language: php

php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update
    - travis_retry composer clear-cache
    - composer config -g github-oauth.github.com 4afc75c666dce51ae16fb83276f8d1f8709f0a23

install:
    - travis_retry composer install --no-interaction --prefer-dist --dev

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
