<?php
namespace Ronanchilvers\Db\Console\Command;

use Aura\SqlSchema\SchemaInterface;
use DateTime;
use Nette\PhpGenerator\PhpNamespace;
use Ronanchilvers\Db\Model;
use Ronanchilvers\Db\Model\Generator;
use Ronanchilvers\Utility\Str;
use RuntimeException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Finder\Finder;

class GenerateCommand extends Command
{
    /**
     * @var \Aura\SqlSchema\SchemaInterface
     */
    protected $schema;

    /**
     * Class constructor
     *
     * @author Ronan Chilvers <ronan@d3r.com>
     */
    public function __construct(SchemaInterface $schema, $name = null)
    {
        parent::__construct($name);
        $this->schema = $schema;
    }

    protected function configure()
    {
        $this->setName('generate')
            ->setDescription('Generate model classes')
            ->addArgument(
                'output_dir',
                InputArgument::REQUIRED,
                'The directory in which to store the generate code'
            )
            ->addOption(
                'namespace',
                null,
                InputOption::VALUE_REQUIRED,
                'The namespace to use for the generated classes',
                'App'
            )
            ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $outputDir = $input->getArgument('output_dir');
        if (!is_dir($outputDir)) {
            throw new RuntimeException(
                sprintf('Output directory %s does not exist', $outputDir)
            );
        }
        $outputDir = realpath($outputDir);

        $tables = $this->schema->fetchTableList();
        $output->writeln(sprintf('generating models for %d tables', count($tables)));

        // Generate models for classes extending Model
        $now = (new DateTime())->format('Y-m-d H:i:s');
        foreach ($tables as $table) {
            $output->write('table : ' . $table);
            $dbColumns = $this->schema->fetchTableCols($table);

            // Generate a model name - the singular of the table name
            $modelName = Str::pascal(rtrim($table, 's'));

            // Create the namespace
            $namespace = new PhpNamespace($input->getOption('namespace'));

            // Create the base class definition
            $class = $namespace->addClass($modelName);
            $class
                ->setExtends(Model::class)
                ->addComment('Auto-generated by ronanchilvers/db')
                ->addComment('Table : ' . $table)
                ->addComment('Generated : ' . $now)
                ;

            // Create accessors
            $primaryKey = null;
            $columns = $data = [];
            foreach ($dbColumns as $column) {
                if ($column->primary) {
                    $primaryKey = $column->name;
                }
                $columns[$column->name] = [
                    'required' => $column->notnull,
                ];
                $data[$column->name] = null;
            }

            $class
                ->addProperty('table', $table)
                ->setVisibility('public')
                ->setStatic()
                ->addComment('@var string')
                ;
            $class
                ->addProperty('primaryKey', $primaryKey)
                ->setVisibility('public')
                ->setStatic()
                ->addComment('@var string')
                ;
            $class
                ->addProperty('columns', $columns)
                ->setVisibility('protected')
                ->addComment('@var array')
                ;
            $class
                ->addProperty('data', $data)
                ->setVisibility('protected')
                ->addComment('@var array')
                ;

            $classString = "<?php\n\n{$namespace}";
            $classString = str_replace("\n\n}", '}', $classString);
            $result = file_put_contents(
                $outputDir . '/' . $modelName . '.php',
                $classString
            );
            if (!$result) {
                throw new RuntimeException(
                    sprintf('Unable to write class file for table %s', $table)
                );
            }
            $output->writeln(' - done');
        }
    }
}
